#!/bin/bash
#SBATCH --gpus 1
#SBATCH -t 2-00:00:00
#SBATCH -A Berzelius-2022-230
#SBATCH --mail-type=ALL
#SBATCH --mail-user ho-yeung.chim.2766@student.uu.se

module load Anaconda/2021.05-nsc1
conda activate /proj/berzelius-2021-29/users/x_hoych/conda_molpc-imp
#conda activate /proj/berzelius-2021-29/users/x_hoych/conda_af_v2.3

#export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$CONDA_PREFIX/lib/

cd /proj/berzelius-2021-29/users/x_hoych/molpc-imp

bash pipeline.sh data/2BL2.fasta


